---
- name: My test playbook
  hosts: all
  become: true
  tasks:
    - name: add a list of users
      user: name='{{item}}' state=present
      with_items:
       - raj
       - Raju
       - ritesh

