---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: Stopping httpd
    service:
      name: httpd
      state: stopped
    notify: Uninstall httpd

  handlers:
  - name: Uninstall httpd
    yum:
      name: httpd
      state: removed    
