---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: installed
  - name: Start httpd service
    service:
      name: httpd
      state: started
